server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  freemarker:
    charset: UTF-8
    suffix: .ftl
    template-loader-path: classpath:/templates
  datasource:
    name: zestdemo
    url: jdbc:h2:mem:zestdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    schema: classpath:zest/schema_h2.sql
