server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  datasource:
    name: zestdemo
    url: jdbc:mysql://localhost:3306/zestdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: zestdemo
    password: zestdemo
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: select 1 from dual
  data:
    mongodb:
      uri: mongodb://localhost:27017/zestdemo
  redis:
    database: 0
    host: localhost
    port: 7000

mybatis:
  mapper-locations: classpath:com/github/bookong/example/zest/springboot/base/mapper/*.xml

zestdemo:
  token: F2020
